# Generated by repro: do not edit by hand
# Please edit Dockerfiles in .repro/
FROM rocker/verse:4.2.2
WORKDIR /home/rstudio
RUN apt-get update -y && apt-get install -y rsync
RUN tlmgr install collection-latexrecommended
RUN install2.r --error --skipinstalled \ 
  here \ 
  patchwork \ 
  qrcode \ 
  showtext \ 
  stargazer \ 
  svglite \ 
  tidyverse \ 
  xaringanthemer
RUN installGithub.r \ 
  aaronpeikert/repro@fc7e884
